<?php

/**
 * @file
 * Register some themes and theme suggestions for the crossword module.
 */

/**
 * Implements hook_theme().
 */
function crossword_theme($existing, $type, $theme, $path) {
  return [
    'crossword' => [
      'variables' => [
        'content' => NULL,
        'attributes' => [],
      ],
    ],
    'crossword_solution' => [
      'variables' => [
        'content' => NULL,
        'attributes' => [],
      ],
    ],
    'crossword_controls' => [
      'variables' => [
        'content' => NULL,
        'attributes' => [],
      ],
    ],
    'crossword_grid' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'crossword_grid_row' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'crossword_square' => [
      'variables' => [
        'fill' => NULL,
        'numeral' => NULL,
        'attributes' => [],
      ],
    ],
    'crossword_clue' => [
      'variables' => [
        'text' => NULL,
        'numeral' => NULL,
        'attributes' => [],
      ],
    ],
    'crossword_clues' => [
      'variables' => [
        'content' => NULL,
        'direction' => NULL,
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_hook_alter().
 *  Makes it easier to theme across clues and down clues separately.
 */
function crossword_theme_suggestions_crossword_clues_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'crossword_clues__' . $variables['direction'];
}
