<?php

/**
 * @file
 * Register some themes and theme suggestions for the crossword module.
 */


/**
 * Implements hook_theme().
 */
function crossword_theme($existing, $type, $theme, $path) {
  return array (
    'crossword' => array(
      'variables' => array(
        'content' => NULL,
        'attributes' => [],
      ),
    ),
    'crossword_solution' => array(
      'variables' => array(
        'content' => NULL,
        'attributes' => [],
      ),
    ),
    'crossword_controls' => array(
      'variables' => array(
        'content' => NULL,
        'attributes' => [],
      ),
    ),
    'crossword_grid' => array(
      'variables' => array(
        'content' => NULL,
      ),
    ),
    'crossword_grid_row' => array(
      'variables' => array(
        'content' => NULL,
      ),
    ),
    'crossword_square' => array(
      'variables' => array(
        'fill' => NULL,
        'numeral' => NULL,
        'attributes' => [],
      ),
    ),
    'crossword_clue' => array(
      'variables' => array(
        'text' => NULL,
        'numeral' => NULL,
        'attributes' => [],
      ),
    ),
    'crossword_clues' => array(
      'variables' => array(
        'content' => NULL,
        'direction' => NULL,
        'attributes' => [],
      ),
    ),
  );
}

 /**
  *  Implements hook_theme_suggestions_hook_alter().
  *  Makes it easier to theme across clues and down clues separately.
  */
function crossword_theme_suggestions_crossword_clues_alter(array &$suggestions, array $variables) {
 $suggestions[] = 'crossword_clues__' . $variables['direction'];
}
